[versions]
minecraft = "1.20.4-R0.1-SNAPSHOT"
[plugins]
userdev = { id = "io.papermc.paperweight.userdev", version = "1.5.11" }
runpaper = { id = "xyz.jpenilla.run-paper", version = "2.2.2" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
lombok = { id = "io.freefair.lombok", version = "8.4" }
hangar = { id = "io.papermc.hangar-publish-plugin", version = "0.1.1" }
minotaur = { id = "com.modrinth.minotaur", version = "2.8.7" }
paperyml = { id = "net.minecrell.plugin-yml.paper", version = "0.6.0" }
pluginyml = { id = "net.minecrell.plugin-yml.bukkit", version = "0.6.0" }
[libraries]
annotations = { module = "org.jetbrains:annotations", version = "24.0.1" }
jedis = { module = "redis.clients:jedis", version = "4.1.1" }
miniplaceholders = { module = "io.github.miniplaceholders:miniplaceholders-api", version = "2.2.3" }
commandframework = { module = "cloud.commandframework:cloud-paper", version = "1.8.4" }
configlib = { module = "de.exlll:configlib-yaml", version = "4.5.0" }
guice = { module = "com.google.inject:guice", version = "7.0.0" }
luckperms = { module = "net.luckperms:api", version = "5.4" }
bstats = { module = "org.bstats:bstats-bukkit", version = "3.0.2" }
hikaridb = { module = "com.zaxxer:HikariCP", version = "5.0.1" }
placeholderapi = { module = "me.clip:placeholderapi", version = "2.11.3" }
stringsimilarity = { module = "net.ricecode:string-similarity", version = "1.0.0" }
ultrapermissions = { module = "me.TechsCode:UltraPermissionsAPI", version = "5.5.2" }