name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - run: chmod +x gradlew
      - name: Build project
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.1.1'
          arguments: build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: build/libs/**.jar
      - name: Generating Changelog
        uses: ardalanamini/auto-changelog@v4
        id: changelog
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/**.jar
          body: ${{ steps.changelog.outputs.changelog }}
          draft: true
      - name: Publish to Modrinth
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.1.1'
          arguments: modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          MODRINTH_CHANGELOG: ${{ steps.changelog.outputs.changelog }}
      - name: Publish to Hangar
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.1.1'
          arguments: publishAllPublicationsToHangar
        env:
          HANGAR_CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          HANGAR_TOKEN: ${{ secrets.HANGAR_TOKEN }}